[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
ignore_missing_imports = true
strict_optional = true
pretty = true

